# Schema for the configuration files of the User registration password module.

user_registrationpassword.settings:
  type: config_object
  label: 'User registration password settings'
  mapping:
    registration:
      type: string
      label: 'User registration password type'
    register_subject:
      type: string
      label: 'Register subject'
    register_body:
      type: string
      label: 'Register body'
    registration_ftll_expire:
      type: boolean
      label: 'Expire activation link'
    registration_ftll_timeout:
      type: integer
      label: 'Expire activation timeout'
